# Discord Bot Configuration
discord:
  ownerID: "654646115072737303"
  status: "Your Custom Status Here"
  token: "YOUR_DISCORD_BOT_TOKEN"
  guild-id: "YOUR_GUILD_ID"
  boostperks:
    allowedRole: "YOUR_REQUIRED_ROLE_ID"
    minecraftCommand: "give {name} minecraft:diamond 1"
  balancedperks:
    allowedRole: "YOUR_REQUIRED_ROLE_ID"
    minecraftCommand: "give {name} minecraft:diamond 1"
  steadyperks:
    allowedRole: "YOUR_REQUIRED_ROLE_ID"
    minecraftCommand: "give {name} minecraft:diamond 1"

# Server status configuration default server used by /serverstatus and /serverstatusembed
server-status:
  ip: "your.server.ip"
  port: 25565
  timeout-seconds: 5
